# Generated by Django 4.1.2 on 2022-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='Asatidz',
            field=models.TextField(default='mantap'),
        ),
    ]
